# Generated by Django 5.2.1 on 2025-05-30 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_org', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('raised', 'Raised'), ('approved', 'Approved'), ('in progress', 'In Progress'), ('delivered', 'Delivered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lead', 'Lead'), ('member', 'Member'), ('purchaser', 'Purchaser')], max_length=25),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('approved', 'Approved'), ('in progress', 'In Progress'), ('delivered', 'Delivered')], max_length=25)),
                ('date', models.DateField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.project')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_raised', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.supplier')),
            ],
        ),
    ]
