# Generated by Django 5.2.1 on 2025-05-30 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_supplier_alter_task_priority_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
