# Generated by Django 5.2.1 on 2025-05-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_alter_purchase_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_org',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
